from app.database import Base,engine,SessionLocal
from app.models import *
from app.engine import prioritize
Base.metadata.drop_all(engine);Base.metadata.create_all(engine);d=SessionLocal()
P=[Product(sku='WM-001',name='Wireless Mouse',category='Accessories',stock=72,reserved=18,reorder=25,zone='A'),Product(sku='KB-002',name='Mechanical Keyboard',category='Accessories',stock=19,reserved=14,reorder=20,zone='B'),Product(sku='WC-003',name='HD Webcam',category='Cameras',stock=0,reserved=0,reorder=15,zone='C'),Product(sku='UH-004',name='USB-C Hub',category='Accessories',stock=27,reserved=8,reorder=20,zone='A'),Product(sku='HS-005',name='Wireless Headset',category='Audio',stock=44,reserved=10,reorder=18,zone='C'),Product(sku='MN-006',name='24-inch Monitor',category='Displays',stock=16,reserved=5,reorder=10,zone='D')];d.add_all(P);d.commit()
data=[('ORD-1042','Priya Retail','Express',4,18998,[(0,10),(1,2)]),('ORD-1048','Tech Corner','Standard',18,7495,[(0,5),(3,2)]),('ORD-1051','Startup Hub','Express',9,15996,[(4,3)]),('ORD-1057','Apex Systems','Standard',30,3299,[(2,1)]),('ORD-1062','Design Lab','Express',12,27997,[(5,2)]),('ORD-1069','Campus Store','Standard',20,5497,[(1,1),(3,2)]),('ORD-1075','MediaWorks','Express',6,8598,[(4,1)])]
for n,c,dl,sla,v,items in data:
 o=Order(number=n,customer=c,delivery=dl,sla=sla,value=v);d.add(o);d.flush();[d.add(Item(order_id=o.id,product_id=P[j].id,qty=q)) for j,q in items];prioritize(o)
d.add_all([ExceptionItem(order_number='ORD-1042',type='Missing Item',severity='High',description='Expected 2 mouse units; picker found 1.',recommendation='Search bin A-14, reconcile stock, retry allocation.'),ExceptionItem(order_number='ORD-1051',type='Damaged Item',severity='Medium',description='One headset carton is damaged.',recommendation='Remove damaged quantity and inspect replacement stock.'),ExceptionItem(order_number='ORD-1069',type='Stock Mismatch',severity='High',description='Physical keyboard count differs from system.',recommendation='Freeze allocation and perform an inventory audit.')]);d.commit();print('Demo database created')
